stages:
  - build

.build-image: &build-image
  stage: build
  image: registry.gitlab.com/nosceon/rpi-images/build-tools:gitlab
  script:
    - gcloud auth activate-service-account --key-file=${GOOGLE_CREDENTIALS}
    - /usr/sbin/update-binfmts --enable qemu-arm >/dev/null 2>&1
    - /bin/packer build -var-file=packer/variables.json packer/${TARGET_ARTIFACT}.json
    - mv output-arm-image/image output-arm-image/${TARGET_ARTIFACT}.iso
    - mkdir dist && tar -czvf dist/rpi-${TARGET_ARTIFACT}.tgz -C output-arm-image rpi-${TARGET_ARTIFACT}.iso
    - |
      if [ -z ${CI_COMMIT_TAG+x} ]; then
        gsutil cp dist/rpi-${TARGET_ARTIFACT}.tgz gs://${GCS_BUCKET}/${CI_PROJECT_NAME}/${CI_COMMIT_SHORT_SHA}/rpi-${TARGET_ARTIFACT}-${CI_COMMIT_SHORT_SHA}.tgz
      else
        gsutil cp dist/rpi-${TARGET_ARTIFACT}.tgz gs://${GCS_RELEASE_BUCKET}/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/rpi-${TARGET_ARTIFACT}-${CI_COMMIT_TAG}.tgz
      fi
  tags:
    - packer-arm
  only:
    - master
    - /^v[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]?$/

Build Consul:
  <<: *build-image
  variables:
    TARGET_ARTIFACT: consul

Build Vault:
  <<: *build-image
  variables:
    TARGET_ARTIFACT: vault

Build Nomad:
  <<: *build-image
  variables:
    TARGET_ARTIFACT: nomad

Build Nomad Client:
  <<: *build-image
  variables:
    TARGET_ARTIFACT: nomad-client

Build Hashi Stack:
  <<: *build-image
  variables:
    TARGET_ARTIFACT: hashi-stack

Build Hashi Stack Ext:
  <<: *build-image
  variables:
    TARGET_ARTIFACT: hashi-stack-ext