#cloud-config
# vim: syntax=yaml
#

hostname: consul-svr

manage_etc_hosts: true
package_update: false
package_upgrade: false

write_files:
- path: /etc/consul.d/consul.hcl
  owner: consul:consul
  content: |
    advertise_addr = "{{ GetPrivateInterfaces | include \"type\" \"IP\" | attr \"address\" }}"
    client_addr = "0.0.0.0"
    data_dir = "/opt/consul"
    bootstrap_expect = 3
    retry_join = [ "consul-svr-1.local", "consul-svr-2.local", "consul-svr-3.local" ]
    server = true
    ui = true

runcmd:
- [ raspi-config, nonint, do_ssh, '0' ]